//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMessage.Server {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Datas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Datas() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMessage.Server.Datas", typeof(Datas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;EmployeeID&quot;:1,&quot;LastName&quot;:&quot;Davolio&quot;,&quot;FirstName&quot;:&quot;Nancy&quot;,&quot;Title&quot;:&quot;Sales Representative&quot;,&quot;TitleOfCourtesy&quot;:&quot;Ms.&quot;,&quot;BirthDate&quot;:&quot;1968-12-08T00:00:00&quot;,&quot;HireDate&quot;:&quot;1992-05-01T00:00:00&quot;,&quot;Address&quot;:&quot;507 - 20th Ave. E.\nApt. 2A&quot;,&quot;City&quot;:&quot;Seattle&quot;,&quot;Region&quot;:&quot;WA&quot;,&quot;PostalCode&quot;:&quot;98122&quot;,&quot;Country&quot;:&quot;USA&quot;,&quot;HomePhone&quot;:&quot;(206) 555-9857&quot;,&quot;Extension&quot;:&quot;5467&quot;,&quot;Photo&quot;:null,&quot;Notes&quot;:&quot;Education includes a BA in psychology from Colorado State University.  She also completed \&quot;The Art of the Cold Call.\&quot;  Nancy is a member of Toastmasters [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
    }
}
